### ISSUE TITLE
Remove polyfill.io link in mkdocs.yml

### ISSUE THREAD

**Issue by milkyway-git** [PHPOffice/Math#14]
polyfill.io supply chain attack, see 

- https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/
- https://github.com/polyfillpolyfill/polyfill-service/issues/2873
- https://sansec.io/research/polyfill-supply-chain-attack

mkdocs.yml links to https://polyfill.io in the extra_javascript section.

I know nothing about mkdocs, but this dependency should be removed.

**Comment by Daniel15** [comment]
The only polyfills it's loading are the ES6 polyfills, which aren't needed as all browsers have supported ES6 functionality for nearly 10 years now.

**Comment by Progi1984** [comment]
Thanks @milkyway-git & @Daniel15 ! It's done in 0f62d45.

**Comment by vtulse** [comment]
Hello Team,
Any plan to release the polyfill changes?
